// <auto-generated />
using System;
using IDS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace IDS.API.Migrations
{
    [DbContext(typeof(IDSAppContext))]
    partial class IDSAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("idsapp")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("IDS.Domain.AggregateModels.IdentityServerAggregate.IdentityGrant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IdentityGrant");
                });

            modelBuilder.Entity("IDS.Domain.AggregateModels.UserAggregate.Identity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Modifier")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Identity");

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            CreatedTime = new DateTime(2020, 3, 30, 14, 22, 42, 200, DateTimeKind.Utc).AddTicks(5032),
                            Creator = "admin",
                            Email = "bamboo@bamboo.com",
                            ModifiedTime = new DateTime(2020, 3, 30, 14, 22, 42, 200, DateTimeKind.Utc).AddTicks(5032),
                            Modifier = "admin",
                            Name = "Admin",
                            OrganizationId = "bamboo",
                            Password = "e10adc3949ba59abbe56e057f20f883e",
                            Phone = "157",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("IDS.Domain.AggregateModels.UserAggregate.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ActivationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Creator")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Mail")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Modifier")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organization");

                    b.HasData(
                        new
                        {
                            Id = "bamboo",
                            ActivationTime = new DateTime(2019, 3, 30, 22, 22, 42, 205, DateTimeKind.Local).AddTicks(6653),
                            CreatedTime = new DateTime(2020, 3, 30, 14, 22, 42, 206, DateTimeKind.Utc).AddTicks(3968),
                            Creator = "admin",
                            Description = "",
                            ExpireTime = new DateTime(2120, 3, 30, 22, 22, 42, 205, DateTimeKind.Local).AddTicks(6529),
                            Mail = "bamboo@bamboo",
                            ModifiedTime = new DateTime(2020, 3, 30, 14, 22, 42, 206, DateTimeKind.Utc).AddTicks(3968),
                            Modifier = "admin",
                            Name = "竹烛",
                            OwnerId = "admin",
                            Phone = "157"
                        });
                });

            modelBuilder.Entity("IDS.Domain.AggregateModels.UserAggregate.Identity", b =>
                {
                    b.HasOne("IDS.Domain.AggregateModels.UserAggregate.Organization", "Organization")
                        .WithMany("OwnAccounts")
                        .HasForeignKey("OrganizationId");
                });
#pragma warning restore 612, 618
        }
    }
}
